
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Aircraft : Luban.BeanBase
{
    public Aircraft(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ThrusterId = _buf.ReadInt();
        WeaponId0 = _buf.ReadInt();
        WeaponId1 = _buf.ReadInt();
        WeaponId2 = _buf.ReadInt();
        ArmorId0 = _buf.ReadInt();
        ArmorId1 = _buf.ReadInt();
        ArmorId2 = _buf.ReadInt();
        DeadEffectId = _buf.ReadInt();
        DeadSoundId = _buf.ReadInt();
    }

    public static Aircraft DeserializeAircraft(ByteBuf _buf)
    {
        return new Aircraft(_buf);
    }

    /// <summary>
    /// 战机编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 推进器编号
    /// </summary>
    public readonly int ThrusterId;
    /// <summary>
    /// 武器编号0
    /// </summary>
    public readonly int WeaponId0;
    /// <summary>
    /// 武器编号1
    /// </summary>
    public readonly int WeaponId1;
    /// <summary>
    /// 武器编号2
    /// </summary>
    public readonly int WeaponId2;
    /// <summary>
    /// 装甲编号0
    /// </summary>
    public readonly int ArmorId0;
    /// <summary>
    /// 装甲编号1
    /// </summary>
    public readonly int ArmorId1;
    /// <summary>
    /// 装甲编号2
    /// </summary>
    public readonly int ArmorId2;
    /// <summary>
    /// 死亡特效编号
    /// </summary>
    public readonly int DeadEffectId;
    /// <summary>
    /// 死亡声音编号
    /// </summary>
    public readonly int DeadSoundId;
   
    public const int __ID__ = -624194762;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "thrusterId:" + ThrusterId + ","
        + "weaponId0:" + WeaponId0 + ","
        + "weaponId1:" + WeaponId1 + ","
        + "weaponId2:" + WeaponId2 + ","
        + "armorId0:" + ArmorId0 + ","
        + "armorId1:" + ArmorId1 + ","
        + "armorId2:" + ArmorId2 + ","
        + "deadEffectId:" + DeadEffectId + ","
        + "deadSoundId:" + DeadSoundId + ","
        + "}";
    }
}

}

