
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Armor : Luban.BeanBase
{
    public Armor(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        MaxHp = _buf.ReadInt();
        Defense = _buf.ReadInt();
    }

    public static Armor DeserializeArmor(ByteBuf _buf)
    {
        return new Armor(_buf);
    }

    /// <summary>
    /// 装甲编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 最大生命
    /// </summary>
    public readonly int MaxHp;
    /// <summary>
    /// 防御力
    /// </summary>
    public readonly int Defense;
   
    public const int __ID__ = 63533343;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "maxHp:" + MaxHp + ","
        + "defense:" + Defense + ","
        + "}";
    }
}

}

