
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Asteroid : Luban.BeanBase
{
    public Asteroid(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        MaxHp = _buf.ReadInt();
        Attack = _buf.ReadInt();
        Speed = _buf.ReadFloat();
        AngularSpeed = _buf.ReadFloat();
        DeadEffectId = _buf.ReadInt();
        DeadSoundId = _buf.ReadInt();
    }

    public static Asteroid DeserializeAsteroid(ByteBuf _buf)
    {
        return new Asteroid(_buf);
    }

    /// <summary>
    /// 小行星编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 最大生命
    /// </summary>
    public readonly int MaxHp;
    /// <summary>
    /// 冲击力
    /// </summary>
    public readonly int Attack;
    /// <summary>
    /// 速度
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 角速度
    /// </summary>
    public readonly float AngularSpeed;
    /// <summary>
    /// 死亡特效编号
    /// </summary>
    public readonly int DeadEffectId;
    /// <summary>
    /// 死亡声音编号
    /// </summary>
    public readonly int DeadSoundId;
   
    public const int __ID__ = -279973669;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "maxHp:" + MaxHp + ","
        + "attack:" + Attack + ","
        + "speed:" + Speed + ","
        + "angularSpeed:" + AngularSpeed + ","
        + "deadEffectId:" + DeadEffectId + ","
        + "deadSoundId:" + DeadSoundId + ","
        + "}";
    }
}

}

