
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    private TbEntity m_TbEntity;
    public TbEntity TbEntity 
    {
        get
        {
            if (m_TbEntity == null)
            {
                m_TbEntity = new TbEntity(byteBufLoader("tbentity"));
                m_TbEntity.ResolveRef(this);
            }
            return m_TbEntity;
        }
        set
        {
            m_TbEntity = value;
            m_TbEntity.ResolveRef(this);
        }
    }
    private TbMusic m_TbMusic;
    public TbMusic TbMusic 
    {
        get
        {
            if (m_TbMusic == null)
            {
                m_TbMusic = new TbMusic(byteBufLoader("tbmusic"));
                m_TbMusic.ResolveRef(this);
            }
            return m_TbMusic;
        }
        set
        {
            m_TbMusic = value;
            m_TbMusic.ResolveRef(this);
        }
    }
    private TbScene m_TbScene;
    public TbScene TbScene 
    {
        get
        {
            if (m_TbScene == null)
            {
                m_TbScene = new TbScene(byteBufLoader("tbscene"));
                m_TbScene.ResolveRef(this);
            }
            return m_TbScene;
        }
        set
        {
            m_TbScene = value;
            m_TbScene.ResolveRef(this);
        }
    }
    private TbSound m_TbSound;
    public TbSound TbSound 
    {
        get
        {
            if (m_TbSound == null)
            {
                m_TbSound = new TbSound(byteBufLoader("tbsound"));
                m_TbSound.ResolveRef(this);
            }
            return m_TbSound;
        }
        set
        {
            m_TbSound = value;
            m_TbSound.ResolveRef(this);
        }
    }
    private TbUIForm m_TbUIForm;
    public TbUIForm TbUIForm 
    {
        get
        {
            if (m_TbUIForm == null)
            {
                m_TbUIForm = new TbUIForm(byteBufLoader("tbuiform"));
                m_TbUIForm.ResolveRef(this);
            }
            return m_TbUIForm;
        }
        set
        {
            m_TbUIForm = value;
            m_TbUIForm.ResolveRef(this);
        }
    }
    private TbUISound m_TbUISound;
    public TbUISound TbUISound 
    {
        get
        {
            if (m_TbUISound == null)
            {
                m_TbUISound = new TbUISound(byteBufLoader("tbuisound"));
                m_TbUISound.ResolveRef(this);
            }
            return m_TbUISound;
        }
        set
        {
            m_TbUISound = value;
            m_TbUISound.ResolveRef(this);
        }
    }
    private TbAircraft m_TbAircraft;
    public TbAircraft TbAircraft 
    {
        get
        {
            if (m_TbAircraft == null)
            {
                m_TbAircraft = new TbAircraft(byteBufLoader("tbaircraft"));
                m_TbAircraft.ResolveRef(this);
            }
            return m_TbAircraft;
        }
        set
        {
            m_TbAircraft = value;
            m_TbAircraft.ResolveRef(this);
        }
    }
    private TbArmor m_TbArmor;
    public TbArmor TbArmor 
    {
        get
        {
            if (m_TbArmor == null)
            {
                m_TbArmor = new TbArmor(byteBufLoader("tbarmor"));
                m_TbArmor.ResolveRef(this);
            }
            return m_TbArmor;
        }
        set
        {
            m_TbArmor = value;
            m_TbArmor.ResolveRef(this);
        }
    }
    private TbAsteroid m_TbAsteroid;
    public TbAsteroid TbAsteroid 
    {
        get
        {
            if (m_TbAsteroid == null)
            {
                m_TbAsteroid = new TbAsteroid(byteBufLoader("tbasteroid"));
                m_TbAsteroid.ResolveRef(this);
            }
            return m_TbAsteroid;
        }
        set
        {
            m_TbAsteroid = value;
            m_TbAsteroid.ResolveRef(this);
        }
    }
    private TbThruster m_TbThruster;
    public TbThruster TbThruster 
    {
        get
        {
            if (m_TbThruster == null)
            {
                m_TbThruster = new TbThruster(byteBufLoader("tbthruster"));
                m_TbThruster.ResolveRef(this);
            }
            return m_TbThruster;
        }
        set
        {
            m_TbThruster = value;
            m_TbThruster.ResolveRef(this);
        }
    }
    private TbWeapon m_TbWeapon;
    public TbWeapon TbWeapon 
    {
        get
        {
            if (m_TbWeapon == null)
            {
                m_TbWeapon = new TbWeapon(byteBufLoader("tbweapon"));
                m_TbWeapon.ResolveRef(this);
            }
            return m_TbWeapon;
        }
        set
        {
            m_TbWeapon = value;
            m_TbWeapon.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, ByteBuf> byteBufLoader;
    System.Func<string, JSONNode> jsonLoader;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }

    public Tables(System.Func<string, JSONNode> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }
    
    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        byteBufLoader = null;
        byteBufLoader = loader;
    }

    public void SetDefaultLoader(System.Func<string, JSONNode> loader)
    {
        jsonLoader = null;
        jsonLoader = loader;
    }

    //public partial void Init();

    public void Init(){}
}

}
