
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Thruster : Luban.BeanBase
{
    public Thruster(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Speed = _buf.ReadFloat();
    }

    public static Thruster DeserializeThruster(ByteBuf _buf)
    {
        return new Thruster(_buf);
    }

    /// <summary>
    /// 推进器编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 速度
    /// </summary>
    public readonly float Speed;
   
    public const int __ID__ = 1553598245;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "speed:" + Speed + ","
        + "}";
    }
}

}

